// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-txSnCHB9rgj4kuImilaAlrX146-3BSQ',
    appId: '1:283650881747:web:84d8be9465fe5d03db3c26',
    messagingSenderId: '283650881747',
    projectId: 'climate-ark-87fd3',
    authDomain: 'climate-ark-87fd3.firebaseapp.com',
    storageBucket: 'climate-ark-87fd3.appspot.com',
    measurementId: 'G-ERWYD3VN8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqIFS8XLVo7HmxGxQU2vbvPs7P0U0-zw',
    appId: '1:283650881747:android:0d41d5bafaa7427ddb3c26',
    messagingSenderId: '283650881747',
    projectId: 'climate-ark-87fd3',
    storageBucket: 'climate-ark-87fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGOMwlRGAeQKXH7YJvKeOnMCWvO7cm4U',
    appId: '1:283650881747:ios:cb95bcb6d6b9a02edb3c26',
    messagingSenderId: '283650881747',
    projectId: 'climate-ark-87fd3',
    storageBucket: 'climate-ark-87fd3.appspot.com',
    iosClientId: '283650881747-ngf1qb56g047c13lcshoelfdi9crk8jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.canvas',
  );
}
